config/routes.rb
Rails.application.routes.draw do



  post '/renters/:id/edit', to: 'renters#update', as: 'update_renter'
  get '/renter_login', to: "renters#login", as: 'renter_login'
  post '/send_renter_login', to: 'renters#handle_login'
  delete '/renters/logout', to: 'renters#logout', as: 'logout'

  resources :reviews
  resources :leases
  resources :landlords
  resources :renters
  
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get '/', to: 'homepages#home', as: 'homepages'
  root "homepages#home", as: 'homepages'
  
  

  
 

  
  

 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/landlord.rb
class Landlord < ApplicationRecord
    has_many :leases
    has_many :reviews
    has_many :renters, through: :leases

    validates :name, presence: true
    validates :username, presence: true, uniqueness: true
    validates :location, presence: true
    validates :password, presence: true


    has_secure_password

    def average_rating
        landlord_reviews=reviews.all.select {|review| review.landlord_id == self.id}
        ratings_sum=landlord_reviews.sum {|review| review.rating}
        average=ratings_sum/landlord_reviews.count.to_f
        rounded_ave=average.round(1)
    end

end

app/models/lease.rb
class Lease < ApplicationRecord
    belongs_to :renter
    belongs_to :landlord
end

app/models/renter.rb
class Renter < ApplicationRecord
    has_one_attached :avatar
    has_many :leases, dependent: :destroy
    has_many :reviews, dependent: :destroy
    has_many :landlords, through: :leases

    validates :age, numericality: {greater_than_or_equal_to: 18, less_than_or_equal_to: 35}
    validates :name, presence: true
    validates :username, presence: true, uniqueness: true
    validates :password, presence: true

    has_secure_password

    def average_rating
        renter_reviews = reviews.all.select {|review| review.renter_id == self.id}
        ratings_sum = renter_reviews.sum {|review| review.rating}
        average=ratings_sum/renter_reviews.count.to_f
        rounded_ave=average.round(1)
    end
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :renter
    belongs_to :landlord

    validates :rating, numericality: [greater_than: 0, less_than: 11]
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :renter_logged_in?
    # helper_method :renter_authorized
    
    before_action :renter_authorized

    def set_current_renter
        
        @current_renter = Renter.find_by(id: session[:renter_id])
    end

    def renter_logged_in?
        !set_current_renter.nil?
    end


    def renter_authorized
        redirect_to renter_login_path unless renter_logged_in?
    end

    

end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
    skip_before_action :renter_authorized, only: [:home]
    def home

    end 

end

app/controllers/landlords_controller.rb
class LandlordsController < ApplicationController
    
   
    
    

    def index 
        @landlords = Landlord.all
        
    end 

    # we might not need this action thanks to before_action 
    def show 
        @landlord = Landlord.find(params[:id])
    end 

    def new 
        @landlord = Landlord.new 
    end 

    def create
        @landlord = Landlord.create(landlord_params)

        if @landlord.valid?
            session[:landlord_id] = @landlord.id
            redirect_to landlord_path(@landlord)
          
        else 
            flash[:errors] = @landlord.errors.full_messages
            redirect_to new_landlord_path
        end
    end 

    # we might not need this action thanks to before_action 
    def edit 
        @landlord = @current_landlord
        # @landlord = Landlord.find(params[:id])
    end 

    def update 
        # @landlord = Landlord.find(params[:id])
        @landlord.update(landlord_params)

        redirect_to landlord_path(@landlord)
    end 

    def destroy 
        # @landlord = Landlord.find(params[:id])
        @landlord.destroy 
        # byebug
        redirect_to landlords_path
    end 

    private

    def landlord_params 
        params.require(:landlord).permit(:name, :location, :username, :user_type, :password)
    end 

    def get_landlord 
        @landlord = Landlord.find(params[:id])
    end 

end

app/controllers/leases_controller.rb
class LeasesController < ApplicationController

    def show 
        @lease = Lease.find(params[:id])

        # @renter = Renter.find(params[:id])
        # @landlord = Landlord.find(params[:id])
    end 

    def new 
        @lease = Lease.new
        @landlords = Landlord.all 
    end 

    def create 
        @current_renter.leases << Lease.create(lease_params)
    

        redirect_to renter_path(@current_renter)
    end

    private 

    def lease_params 
        params.require(:lease).permit(:landlord_id, :location)
    end 

end

app/controllers/renters_controller.rb
class RentersController < ApplicationController
    before_action :get_renter, only: [:show, :edit, :update, :destroy]
    skip_before_action :renter_authorized, only: [:login, :handle_login, :new, :create]

    def login
        @error = flash[:error]
    end

    def handle_login
        @renter = Renter.find_by(username: params[:username])

        if @renter && @renter.authenticate(params[:password])
            session[:renter_id] = @renter.id
            redirect_to renter_path(@renter)
        else
            flash[:error] = "Incorrect username or password"
            redirect_to renter_login_path
            # ? Are we going to need separate login paths for renter/landlord??
        end
    end

    def logout
        session[:renter_id] = nil
        
        redirect_to homepages_path
    end


    def index 
        @renters = Renter.all 
    end 

    
    # def show 
    #     @current_renter = Renter.find_by(id: session[:student_id])
       
    #     # @landlord = Landlord.find(params[:id])
    # end 

    def new 
        @renter = Renter.new 
    end 

    def create
        @renter = Renter.create(renter_params)

        if @renter.valid?
            session[:renter_id] = @renter.id
            redirect_to renter_path(@renter)
          
        else 
            flash[:errors] = @renter.errors.full_messages
            redirect_to new_renter_path
        end
    end 

     # we might not need this action thanks to before_action 
    def edit 
        # @renter = Renter.find(params[:id])
        @renter = @current_renter
    end 

    def update 
        # @renter = Renter.find(params[:id])
        @renter.update(edit_params)

        redirect_to renter_path(@renter)
    end 

    def destroy
        @renter = @current_renter
        @renter.destroy 

        redirect_to homepages_path
    end 


    private

    def renter_params 
        params.require(:renter).permit(:name, :age, :username, :password, :avatar)
    end
    
    def edit_params
        params.require(:renter).permit(:name, :age, :username, :password, :motto, :train)
    end

    def get_renter
        @renter = Renter.find(params[:id])
    end 
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    def new
        @review = Review.new
        @landlords = Landlord.all
    end

    def create 
        @current_renter.reviews << Review.create(review_params)
    

        redirect_to landlord_path(@current_renter.reviews.last.landlord_id)
    end
    # def edit 
    #     # @renter = Renter.find(params[:id])
    #     @review = @current_renter
    # end 

    # def update 
    #     @review.update(review_params)

    #     redirect_to landlord_path(@review.landlord_id)
    # end 

    # def destroy
    #     @review = Review.find(params[:id])
    #     @review.destroy 

    #     redirect_to renters_path
    # end 

    private

    def review_params
        params.require(:review).permit(:landlord_id,:rating, :comment)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/helpers/landlords_helper.rb
module LandlordsHelper
end

app/helpers/leases_helper.rb
module LeasesHelper
end

app/helpers/renters_helper.rb
module RentersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/homepages/home.html.erb
<div class="homepage_box"> 
    <h1> shady </h1>
    <h1> landlord </h1>
    <%= button_to "login", renter_login_path, method: :get %>
    <%= button_to "register", new_renter_path, method: :get %>
</div>

app/views/landlords/index.html.erb
    <h1> landlords </h1>

    <% @landlords.each do |landlord| %> </p>
        <div class=landlord_box>
            <p> <img src="<%= landlord.img_url %>" alt="<%= landlord.img_url%>"> </p>
            <h1> <%= link_to(landlord.name, landlord_path(landlord)) %> </h1>
        </div>
    <% end %>

app/views/landlords/new.html.erb
<h1> new landlord form </h1>

<br>
<br>

<%= form_for @landlord do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <br>
    <%= f.label :location %>
    <%= f.text_field :location %>
    <br>
    <br>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <br>
    <br>
    <%= f.label :user_type %>
    <%= f.text_field :user_type %>
    <br>
    <br>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <br>
    <br>
    <%= f.submit "submit" %>
<% end %>

app/views/landlords/show.html.erb
<div class=box>
   
    <img src="<%= @landlord.img_url %>" alt="<%= @landlord.img_url%>">
    <h1> <%= @landlord.name %> </h1>
    <h3> 
        <p>username: <%= @landlord.username %></p>
        <p>location: <%= @landlord.location %></p>
        <p>favorite tool: <%= @landlord.tool %></p>
        <p>main hustle: <%= @landlord.hustle %></p>
        <p>shady rating: <%= @landlord.average_rating%></p>
        <%= button_to "start new lease", new_lease_path, method: :get %>
    </h3>
    <audio src= "<%= @landlord.song %>" controls> </audio>
</div>

<br>

<div class=box_two>
    <h5> my tenets: 
        <% @landlord.leases.each do |lease| %>
        <p><%= link_to lease.renter.name, renter_path(lease.renter.id)%></p>
        <% end %>
    </h5>
</div>
<br>
<div class=DivToScroll>
    <div class=DivWithScroll>
        <h5> reviews: 
            <% @landlord.reviews.each do |review| %>
            <p> <%= link_to review.renter.name, renter_path(review.renter.id) %> </p>
            <p> <%= review.comment %> </p>
            <p> shady-ness rating: <%= review.rating %></p>
            <% end %>
            
        </h5>
    </div>
    <br> 
    <%= button_to "leave a review", new_review_path, method: :get %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>shady landlord</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%=  stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#  javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans:ital@1&display=swap" rel="stylesheet">
  </head>

  <body>
  <% unless controller_name == "homepages" || action_name == "login"%>

  <nav >
     <ul>
       <% if renter_logged_in? %>
      
        <li class="nav-tabs first-tab"><%= button_to "renters", renters_path, method: :get%></li>
        <li class="nav-tabs"><%= button_to "landlords", landlords_path, method: :get %></li>
        <li class="nav-tabs right"><%= button_to @current_renter.username, renter_path(@current_renter), method: :get %></li>
        <li class="nav-tabs right"><%= button_to "logout", logout_path, method: :delete %></li>
       <% end %>
 
      
 
       </ul>
    
   </nav>

   
  <% end %>
  


    <%= yield %>
  </body>
</html>

app/views/leases/new.html.erb
<h1> new lease </h1>
<div class=form_box>
    <%= form_for @lease do |f| %>

    <%# f.label :renter_id %>
    <%# f.collection_select :renter_id, Renter.all, :id, :name %>
    Renter: <%= @current_renter.name %>
    <br>
    <br>
    <%= f.label :landlord_id %>
    <%= f.collection_select :landlord_id, @landlords, :id, :name %>
    <br>
    <br>
    <%= f.label :location %>
    <%= f.text_field :location %>
    <br>
    <br>
    <%= f.submit %>
<% end %>
</div>

app/views/renters/edit.html.erb
 
 
 <div class=edit_renter_box>
 <% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <p> <%= error %></p>
  <% end %>
<% end %>

<%= form_for :renter do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<br>
<br>
<%= f.label :age %>
<%= f.number_field :age %>
<br>
<br>
<%= f.label :username %>
<%= f.text_field :username %>
<br>
<br>
<%= f.label :password %>
<%= f.text_field :password %>
<br>
<br>
<%= f.label :motto %>
<%= f.text_field :motto %>
<br>
<br>
<%= f.label "if you were a train what train would you be?" %>
<%= f.text_field :train %>
<br>
<br>
<%= f.submit "save" %>
<% end %>
<br>
<br>
<%= button_to "delete my account", renter_path(@current_renter), method: :delete  %>

</div>

app/views/renters/index.html.erb
<h1> renters </h1>
    
    
    <% @renters.each do |renter| %> </p>
        <div class=landlord_box>
        
            
        <% if renter.avatar.attached? %>
            <img src= "<%= (url_for(renter.avatar)) %>" >
        <% else %>
            <img src="<%= renter.img_url %>" alt="<%= renter.img_url%>">
        <% end %>
            
        <p> <%= link_to(renter.name, renter_path(renter)) %> </p>
       </div>
    <% end %>
   

app/views/renters/login.html.erb
<div class="login_box"> 
        <h1> login form </h1> 

    <br>
    <br>
    <% if @error %>
    <p> <%= @error %> </p>
    <% end %>

    <%= form_tag "/send_renter_login" do %>
        <%= label_tag :username %>
        <%= text_field_tag :username %>
        <br>
        <br>
        <%= label_tag :password %>
        <%= password_field_tag :password %>
        <br>
        <br>
        <%= submit_tag "login" %>
    <% end %>

    <%= button_to "homepage", homepages_path, method: :get %>
</div>

app/views/renters/new.html.erb
<div class="register_box"> 

  <h3> sign up </h3>
    <% if flash[:errors] %>
      <% flash[:errors].each do |error| %>
      <p> <%= error %></p>
    <% end %>
    <% end %>
  <%= form_for @renter do |f| %>
    <%= f.label :name %>
    <br>
    <%= f.text_field :name %>
    <br>
    <%= f.label :age %>
    <br>
    <%= f.number_field :age, in: 18..35 %>
    <br>
    <%= f.label :username %>
    <br>
    <%= f.text_field :username %>
    <br>
    <%= f.label :password %>
    <br>
    <%= f.password_field :password %>
    <br>
    <%= f.label "Profile Photo" %>
    <br>
    <%= f.file_field :avatar %>
    <br>
    <%= f.submit "register" %>
  <% end %>
  <%= button_to "homepage", homepages_path, method: :get %>
  <br>

 

</div>

app/views/renters/show.html.erb
<div class=box>
    <% if @renter.avatar.attached? %>
    <img src= "<%= (url_for(@renter.avatar)) %>" >
    <% else %>
    <img src="<%= @renter.img_url %>" alt="<%= @renter.img_url%>">
    <% end %>
    <h1> <%= @renter.name %> </h1>

    <h3> 
        <p> username: <%= @renter.username %> </p>
        <p> motto: <%= @renter.motto %> </p>
        <p> if i was a train: <%= @renter.train %> </p>
    </h3>

    <h3>
        <%= @renter.username %>'s lease: <% @renter.leases.each do |lease| %>
        <p>landlord: <%= link_to "#{lease.landlord.name}", landlord_path(lease.landlord.id) %> </p>
        <p> address: <%= "#{lease.location}" %> </p>
        <% end %>
    </h3>

    

    <% if @renter == @current_renter %>
    <%= button_to "edit renter", edit_renter_path, method: :get %>
    <% end %>
</div>

app/views/reviews/new.html.erb
<h1> leave a review </h1>

<br>
<div class=review_box>
<%= form_for @review do |f| %>
    <%= f.label :landlord_id %>
    <%= f.collection_select :landlord_id, @landlords, :id, :name %>
    <br> 
    <br>    
    <%= f.label :shady_lvl %>
    <%= f.number_field :rating, in: 1..5%>
    <br>
    <br>
    <%= f.label :comment %>
    <%= f.text_field :comment %>
    <br>
    <br>
    <%= f.submit %>
    <% end %>
</div>